sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t pypointereau/docker-vue-test .

script:
  - docker run pypointereau/docker-vue-test npm run test

  deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-2"
    app: "docker-vue-test"
    env: "docker-vue-test-env"
    bucket_name: "elasticbeanstalk-ap-southeast-2-833430126993"
    bucket_path: "docker-vue-test"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"